import { useQuery } from "@tanstack/react-query"
import { Badge, Container, Heading, Text } from "@medusajs/ui"
import { defineRouteConfig } from "@medusajs/admin-sdk"

type AuditEvent = {
  id: string
  action: string
  outcome: string
  entity_type: string
  entity_id: string
  organization_id?: string | null
  actor_display?: string | null
  actor_type: string
  reason_code?: string | null
  note?: string | null
  occurred_at?: string | null
}

const ActivityPage = () => {
  const query = useQuery({
    queryKey: ["b2b-activity-admin"],
    queryFn: async () => {
      const response = await fetch("/admin/b2b/activity?take=100")
      if (!response.ok) throw new Error("Unable to load activity")
      return (await response.json()) as { audit_events: AuditEvent[]; total: number }
    },
  })
  const events = query.data?.audit_events ?? []

  return (
    <Container className="py-8">
      <Heading>Activity Log</Heading>
      <Text className="text-ui-fg-subtle mt-2 mb-6">Append-only B2B audit events generated by backend workflows.</Text>
      {query.isError && <Text className="text-ui-fg-error mb-4">Unable to load activity.</Text>}
      <div className="rounded-lg border border-ui-border-base divide-y divide-ui-border-base">
        {events.length === 0 ? <Text className="p-4 text-ui-fg-subtle">No activity events returned.</Text> : events.map((event) => (
          <div key={event.id} className="p-4">
            <div className="flex items-start justify-between gap-3"><div><Text className="font-medium">{event.action}</Text><Text className="text-sm text-ui-fg-subtle mt-1">{event.entity_type}: {event.entity_id} · Organization: {event.organization_id ?? "—"}</Text></div><Badge>{event.outcome}</Badge></div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mt-3 text-sm"><Text>Actor: {event.actor_display ?? event.actor_type}</Text><Text>Reason: {event.reason_code ?? "—"}</Text><Text>{event.occurred_at ? new Date(event.occurred_at).toLocaleString() : "—"}</Text></div>
            {event.note && <Text className="text-sm text-ui-fg-subtle mt-2">{event.note}</Text>}
          </div>
        ))}
      </div>
    </Container>
  )
}

export const config = defineRouteConfig({ label: "B2B Activity" })
export default ActivityPage
