import { listB2BAuditEvents } from "@lib/data/b2b"
import { Container, Heading, Text, Button } from "@modules/common/components/ui"
import LocalizedClientLink from "@modules/common/components/localized-client-link"

const outcomeClasses: Record<string, string> = {
  success: "bg-green-100 text-green-800",
  denied: "bg-yellow-100 text-yellow-800",
  failure: "bg-red-100 text-red-800",
}

function formatMetadata(metadata: Record<string, any> | null | undefined) {
  if (!metadata || typeof metadata !== "object") return "—"

  const entries = Object.entries(metadata)
  if (entries.length === 0) return "—"

  return entries
    .slice(0, 4)
    .map(([key, value]) => `${key}: ${typeof value === "string" ? value : JSON.stringify(value)}`)
    .join(" • ")
}

export const metadata = {
  title: "B2B Activity",
  description: "Read-only audit trail for B2B operations and workflow decisions.",
}

export default async function B2BAuditActivityPage() {
  const data = await listB2BAuditEvents({ take: 50 }).catch(() => ({
    audit_events: [],
    count: 0,
    total: 0,
  }))

  const events = data.audit_events || []

  return (
    <Container className="py-12" data-testid="b2b-activity-page">
      <div className="mb-8 flex items-center justify-between gap-3">
        <div>
          <Heading level="h1">Activity log</Heading>
          <Text className="mt-2 text-ui-fg-muted">
            Read-only audit trail generated by the backend for B2B workflow decisions and operational actions.
          </Text>
        </div>
      </div>

      {events.length === 0 ? (
        <div className="rounded-lg border border-dashed border-gray-200 p-8 text-center">
          <Text className="text-ui-fg-muted">No audit activity is available yet.</Text>
        </div>
      ) : (
        <div className="space-y-4">
          {events.map((event) => (
            <div key={event.id} className="rounded-lg border border-gray-200 p-4">
              <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                <div className="space-y-2">
                  <div className="flex flex-wrap items-center gap-2">
                    <Text className="font-semibold">{event.action}</Text>
                    <span className={`inline-flex rounded-full px-2 py-1 text-xs font-medium capitalize ${outcomeClasses[event.outcome] || "bg-gray-100 text-gray-800"}`}>
                      {event.outcome}
                    </span>
                  </div>

                  <div className="grid gap-3 md:grid-cols-3">
                    <div>
                      <Text className="text-xs text-ui-fg-muted">Entity</Text>
                      <Text className="mt-1 font-medium">{event.entity_type}</Text>
                    </div>
                    <div>
                      <Text className="text-xs text-ui-fg-muted">Entity ID</Text>
                      <Text className="mt-1 font-medium break-all">{event.entity_id}</Text>
                    </div>
                    <div>
                      <Text className="text-xs text-ui-fg-muted">Occurred</Text>
                      <Text className="mt-1 font-medium">
                        {event.occurred_at ? new Date(event.occurred_at).toLocaleString() : "—"}
                      </Text>
                    </div>
                  </div>
                </div>

                <div className="text-left md:text-right">
                  <Text className="text-xs text-ui-fg-muted">Actor</Text>
                  <Text className="mt-1 font-medium">
                    {event.actor_display || event.actor_id || event.actor_type}
                  </Text>
                </div>
              </div>

              <div className="mt-4 grid gap-3 md:grid-cols-2">
                <div>
                  <Text className="text-xs text-ui-fg-muted">Organization</Text>
                  <Text className="mt-1 font-medium">{event.organization_id || "—"}</Text>
                </div>
                <div>
                  <Text className="text-xs text-ui-fg-muted">Correlation</Text>
                  <Text className="mt-1 font-medium break-all">{event.correlation_id || "—"}</Text>
                </div>
                {event.reason_code && (
                  <div>
                    <Text className="text-xs text-ui-fg-muted">Reason code</Text>
                    <Text className="mt-1 font-medium">{event.reason_code}</Text>
                  </div>
                )}
                {event.note && (
                  <div>
                    <Text className="text-xs text-ui-fg-muted">Note</Text>
                    <Text className="mt-1 font-medium">{event.note}</Text>
                  </div>
                )}
              </div>

              {event.metadata && (
                <div className="mt-4 rounded border border-gray-200 bg-gray-50 p-3">
                  <Text className="text-xs text-ui-fg-muted">Metadata</Text>
                  <Text className="mt-1 text-sm break-words">{formatMetadata(event.metadata)}</Text>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </Container>
  )
}
